-- =============================================================================
-- Arquivo: 01_seed_data.sql
-- Descricao: Dados iniciais (seed) para o sistema
-- Projeto: AFYA PBD26 - Sistema de Prontuario Eletronico do Paciente
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Especialidades medicas
-- -----------------------------------------------------------------------------
INSERT INTO ESPECIALIDADES (ID_ESPECIALIDADE, DESCRICAO, CODIGO_CBO, ATIVO)
VALUES (SEQ_ESPECIALIDADES.NEXTVAL, 'Clinica Geral', '225125', 'S');

INSERT INTO ESPECIALIDADES (ID_ESPECIALIDADE, DESCRICAO, CODIGO_CBO, ATIVO)
VALUES (SEQ_ESPECIALIDADES.NEXTVAL, 'Cardiologia', '225105', 'S');

INSERT INTO ESPECIALIDADES (ID_ESPECIALIDADE, DESCRICAO, CODIGO_CBO, ATIVO)
VALUES (SEQ_ESPECIALIDADES.NEXTVAL, 'Dermatologia', '225110', 'S');

INSERT INTO ESPECIALIDADES (ID_ESPECIALIDADE, DESCRICAO, CODIGO_CBO, ATIVO)
VALUES (SEQ_ESPECIALIDADES.NEXTVAL, 'Endocrinologia', '225115', 'S');

INSERT INTO ESPECIALIDADES (ID_ESPECIALIDADE, DESCRICAO, CODIGO_CBO, ATIVO)
VALUES (SEQ_ESPECIALIDADES.NEXTVAL, 'Gastroenterologia', '225118', 'S');

INSERT INTO ESPECIALIDADES (ID_ESPECIALIDADE, DESCRICAO, CODIGO_CBO, ATIVO)
VALUES (SEQ_ESPECIALIDADES.NEXTVAL, 'Ginecologia e Obstetricia', '225120', 'S');

INSERT INTO ESPECIALIDADES (ID_ESPECIALIDADE, DESCRICAO, CODIGO_CBO, ATIVO)
VALUES (SEQ_ESPECIALIDADES.NEXTVAL, 'Neurologia', '225150', 'S');

INSERT INTO ESPECIALIDADES (ID_ESPECIALIDADE, DESCRICAO, CODIGO_CBO, ATIVO)
VALUES (SEQ_ESPECIALIDADES.NEXTVAL, 'Oftalmologia', '225155', 'S');

INSERT INTO ESPECIALIDADES (ID_ESPECIALIDADE, DESCRICAO, CODIGO_CBO, ATIVO)
VALUES (SEQ_ESPECIALIDADES.NEXTVAL, 'Ortopedia e Traumatologia', '225160', 'S');

INSERT INTO ESPECIALIDADES (ID_ESPECIALIDADE, DESCRICAO, CODIGO_CBO, ATIVO)
VALUES (SEQ_ESPECIALIDADES.NEXTVAL, 'Pediatria', '225165', 'S');

INSERT INTO ESPECIALIDADES (ID_ESPECIALIDADE, DESCRICAO, CODIGO_CBO, ATIVO)
VALUES (SEQ_ESPECIALIDADES.NEXTVAL, 'Psiquiatria', '225170', 'S');

INSERT INTO ESPECIALIDADES (ID_ESPECIALIDADE, DESCRICAO, CODIGO_CBO, ATIVO)
VALUES (SEQ_ESPECIALIDADES.NEXTVAL, 'Urologia', '225185', 'S');

INSERT INTO ESPECIALIDADES (ID_ESPECIALIDADE, DESCRICAO, CODIGO_CBO, ATIVO)
VALUES (SEQ_ESPECIALIDADES.NEXTVAL, 'Oncologia Clinica', '225152', 'S');

INSERT INTO ESPECIALIDADES (ID_ESPECIALIDADE, DESCRICAO, CODIGO_CBO, ATIVO)
VALUES (SEQ_ESPECIALIDADES.NEXTVAL, 'Infectologia', '225130', 'S');

INSERT INTO ESPECIALIDADES (ID_ESPECIALIDADE, DESCRICAO, CODIGO_CBO, ATIVO)
VALUES (SEQ_ESPECIALIDADES.NEXTVAL, 'Medicina do Trabalho', '225140', 'S');

-- -----------------------------------------------------------------------------
-- Usuario administrador padrao do sistema
-- (senha padrao: Admin@2024 - deve ser alterada no primeiro acesso)
-- -----------------------------------------------------------------------------
INSERT INTO USUARIOS (ID_USUARIO, NOME, EMAIL, SENHA_HASH, PERFIL, ATIVO, DT_CRIACAO)
VALUES (
    SEQ_USUARIOS.NEXTVAL,
    'Administrador do Sistema',
    'admin@afya-pbd26.com.br',
    'a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3',
    'ADMIN',
    'S',
    SYSDATE
);

-- -----------------------------------------------------------------------------
-- Exames laboratoriais e de imagem basicos
-- -----------------------------------------------------------------------------
INSERT INTO EXAMES (ID_EXAME, CODIGO, DESCRICAO, TIPO, PREPARACAO, ATIVO)
VALUES (SEQ_EXAMES.NEXTVAL, 'HEMO001', 'Hemograma Completo', 'LABORATORIAL',
        'Jejum de 4 horas', 'S');

INSERT INTO EXAMES (ID_EXAME, CODIGO, DESCRICAO, TIPO, PREPARACAO, ATIVO)
VALUES (SEQ_EXAMES.NEXTVAL, 'BQUI001', 'Glicemia de Jejum', 'LABORATORIAL',
        'Jejum de 8 horas', 'S');

INSERT INTO EXAMES (ID_EXAME, CODIGO, DESCRICAO, TIPO, PREPARACAO, ATIVO)
VALUES (SEQ_EXAMES.NEXTVAL, 'BQUI002', 'Colesterol Total e Fracoes', 'LABORATORIAL',
        'Jejum de 12 horas', 'S');

INSERT INTO EXAMES (ID_EXAME, CODIGO, DESCRICAO, TIPO, PREPARACAO, ATIVO)
VALUES (SEQ_EXAMES.NEXTVAL, 'BQUI003', 'Triglicerideos', 'LABORATORIAL',
        'Jejum de 12 horas', 'S');

INSERT INTO EXAMES (ID_EXAME, CODIGO, DESCRICAO, TIPO, PREPARACAO, ATIVO)
VALUES (SEQ_EXAMES.NEXTVAL, 'BQUI004', 'Ureia e Creatinina', 'LABORATORIAL',
        'Sem preparo especial', 'S');

INSERT INTO EXAMES (ID_EXAME, CODIGO, DESCRICAO, TIPO, PREPARACAO, ATIVO)
VALUES (SEQ_EXAMES.NEXTVAL, 'BQUI005', 'TGO e TGP (Transaminases)', 'LABORATORIAL',
        'Sem preparo especial', 'S');

INSERT INTO EXAMES (ID_EXAME, CODIGO, DESCRICAO, TIPO, PREPARACAO, ATIVO)
VALUES (SEQ_EXAMES.NEXTVAL, 'BQUI006', 'TSH e T4 Livre (Tireoide)', 'LABORATORIAL',
        'Sem preparo especial', 'S');

INSERT INTO EXAMES (ID_EXAME, CODIGO, DESCRICAO, TIPO, PREPARACAO, ATIVO)
VALUES (SEQ_EXAMES.NEXTVAL, 'BQUI007', 'HbA1c (Hemoglobina Glicada)', 'LABORATORIAL',
        'Sem preparo especial', 'S');

INSERT INTO EXAMES (ID_EXAME, CODIGO, DESCRICAO, TIPO, PREPARACAO, ATIVO)
VALUES (SEQ_EXAMES.NEXTVAL, 'URIN001', 'Urina Tipo I (EAS)', 'LABORATORIAL',
        'Coletar amostra de urina do jato medio', 'S');

INSERT INTO EXAMES (ID_EXAME, CODIGO, DESCRICAO, TIPO, PREPARACAO, ATIVO)
VALUES (SEQ_EXAMES.NEXTVAL, 'IMAG001', 'Raio-X de Torax', 'IMAGEM',
        'Retirar acessorios metalicos', 'S');

INSERT INTO EXAMES (ID_EXAME, CODIGO, DESCRICAO, TIPO, PREPARACAO, ATIVO)
VALUES (SEQ_EXAMES.NEXTVAL, 'IMAG002', 'Eletrocardiograma (ECG)', 'FUNCIONAL',
        'Sem preparo especial', 'S');

INSERT INTO EXAMES (ID_EXAME, CODIGO, DESCRICAO, TIPO, PREPARACAO, ATIVO)
VALUES (SEQ_EXAMES.NEXTVAL, 'IMAG003', 'Ultrassonografia Abdominal Total', 'IMAGEM',
        'Jejum de 6 horas e bexiga cheia', 'S');

INSERT INTO EXAMES (ID_EXAME, CODIGO, DESCRICAO, TIPO, PREPARACAO, ATIVO)
VALUES (SEQ_EXAMES.NEXTVAL, 'IMAG004', 'Tomografia Computadorizada de Cranio', 'IMAGEM',
        'Retirar acessorios metalicos da cabeca', 'S');

INSERT INTO EXAMES (ID_EXAME, CODIGO, DESCRICAO, TIPO, PREPARACAO, ATIVO)
VALUES (SEQ_EXAMES.NEXTVAL, 'IMAG005', 'Ressonancia Magnetica', 'IMAGEM',
        'Retirar todos os objetos metalicos. Informar uso de marcapasso', 'S');

-- -----------------------------------------------------------------------------
-- Medicamentos basicos
-- -----------------------------------------------------------------------------
INSERT INTO MEDICAMENTOS (ID_MEDICAMENTO, NOME_GENERICO, NOME_COMERCIAL, PRINCIPIO_ATIVO,
                           FORMA_FARM, CONCENTRACAO, CONTROLADO, ATIVO)
VALUES (SEQ_MEDICAMENTOS.NEXTVAL, 'Paracetamol', 'Tylenol', 'Paracetamol',
        'COMPRIMIDO', '750mg', 'N', 'S');

INSERT INTO MEDICAMENTOS (ID_MEDICAMENTO, NOME_GENERICO, NOME_COMERCIAL, PRINCIPIO_ATIVO,
                           FORMA_FARM, CONCENTRACAO, CONTROLADO, ATIVO)
VALUES (SEQ_MEDICAMENTOS.NEXTVAL, 'Ibuprofeno', 'Advil', 'Ibuprofeno',
        'COMPRIMIDO', '600mg', 'N', 'S');

INSERT INTO MEDICAMENTOS (ID_MEDICAMENTO, NOME_GENERICO, NOME_COMERCIAL, PRINCIPIO_ATIVO,
                           FORMA_FARM, CONCENTRACAO, CONTROLADO, ATIVO)
VALUES (SEQ_MEDICAMENTOS.NEXTVAL, 'Dipirona Sodica', 'Novalgina', 'Dipirona',
        'COMPRIMIDO', '500mg', 'N', 'S');

INSERT INTO MEDICAMENTOS (ID_MEDICAMENTO, NOME_GENERICO, NOME_COMERCIAL, PRINCIPIO_ATIVO,
                           FORMA_FARM, CONCENTRACAO, CONTROLADO, ATIVO)
VALUES (SEQ_MEDICAMENTOS.NEXTVAL, 'Amoxicilina', 'Amoxil', 'Amoxicilina',
        'CAPSULA', '500mg', 'N', 'S');

INSERT INTO MEDICAMENTOS (ID_MEDICAMENTO, NOME_GENERICO, NOME_COMERCIAL, PRINCIPIO_ATIVO,
                           FORMA_FARM, CONCENTRACAO, CONTROLADO, ATIVO)
VALUES (SEQ_MEDICAMENTOS.NEXTVAL, 'Omeprazol', 'Losec', 'Omeprazol',
        'CAPSULA', '20mg', 'N', 'S');

INSERT INTO MEDICAMENTOS (ID_MEDICAMENTO, NOME_GENERICO, NOME_COMERCIAL, PRINCIPIO_ATIVO,
                           FORMA_FARM, CONCENTRACAO, CONTROLADO, ATIVO)
VALUES (SEQ_MEDICAMENTOS.NEXTVAL, 'Metformina', 'Glifage', 'Cloridrato de Metformina',
        'COMPRIMIDO', '850mg', 'N', 'S');

INSERT INTO MEDICAMENTOS (ID_MEDICAMENTO, NOME_GENERICO, NOME_COMERCIAL, PRINCIPIO_ATIVO,
                           FORMA_FARM, CONCENTRACAO, CONTROLADO, ATIVO)
VALUES (SEQ_MEDICAMENTOS.NEXTVAL, 'Losartana Potassica', 'Cozaar', 'Losartana',
        'COMPRIMIDO', '50mg', 'N', 'S');

INSERT INTO MEDICAMENTOS (ID_MEDICAMENTO, NOME_GENERICO, NOME_COMERCIAL, PRINCIPIO_ATIVO,
                           FORMA_FARM, CONCENTRACAO, CONTROLADO, ATIVO)
VALUES (SEQ_MEDICAMENTOS.NEXTVAL, 'Atorvastatina Calcica', 'Lipitor', 'Atorvastatina',
        'COMPRIMIDO', '20mg', 'N', 'S');

INSERT INTO MEDICAMENTOS (ID_MEDICAMENTO, NOME_GENERICO, NOME_COMERCIAL, PRINCIPIO_ATIVO,
                           FORMA_FARM, CONCENTRACAO, CONTROLADO, ATIVO)
VALUES (SEQ_MEDICAMENTOS.NEXTVAL, 'Clonazepam', 'Rivotril', 'Clonazepam',
        'COMPRIMIDO', '2mg', 'S', 'S');

INSERT INTO MEDICAMENTOS (ID_MEDICAMENTO, NOME_GENERICO, NOME_COMERCIAL, PRINCIPIO_ATIVO,
                           FORMA_FARM, CONCENTRACAO, CONTROLADO, ATIVO)
VALUES (SEQ_MEDICAMENTOS.NEXTVAL, 'Azitromicina', 'Zithromax', 'Azitromicina',
        'COMPRIMIDO', '500mg', 'N', 'S');

-- -----------------------------------------------------------------------------
-- Leitos hospitalares de exemplo
-- -----------------------------------------------------------------------------
INSERT INTO LEITOS (ID_LEITO, CODIGO, ANDAR, ALA, TIPO, STATUS, ATIVO)
VALUES (SEQ_LEITOS.NEXTVAL, 'ENF-101', '1', 'ALA A', 'ENFERMARIA', 'DISPONIVEL', 'S');

INSERT INTO LEITOS (ID_LEITO, CODIGO, ANDAR, ALA, TIPO, STATUS, ATIVO)
VALUES (SEQ_LEITOS.NEXTVAL, 'ENF-102', '1', 'ALA A', 'ENFERMARIA', 'DISPONIVEL', 'S');

INSERT INTO LEITOS (ID_LEITO, CODIGO, ANDAR, ALA, TIPO, STATUS, ATIVO)
VALUES (SEQ_LEITOS.NEXTVAL, 'ENF-103', '1', 'ALA A', 'ENFERMARIA', 'DISPONIVEL', 'S');

INSERT INTO LEITOS (ID_LEITO, CODIGO, ANDAR, ALA, TIPO, STATUS, ATIVO)
VALUES (SEQ_LEITOS.NEXTVAL, 'UTI-001', '2', 'UTI', 'UTI', 'DISPONIVEL', 'S');

INSERT INTO LEITOS (ID_LEITO, CODIGO, ANDAR, ALA, TIPO, STATUS, ATIVO)
VALUES (SEQ_LEITOS.NEXTVAL, 'UTI-002', '2', 'UTI', 'UTI', 'DISPONIVEL', 'S');

INSERT INTO LEITOS (ID_LEITO, CODIGO, ANDAR, ALA, TIPO, STATUS, ATIVO)
VALUES (SEQ_LEITOS.NEXTVAL, 'APT-201', '2', 'ALA B', 'APARTAMENTO', 'DISPONIVEL', 'S');

INSERT INTO LEITOS (ID_LEITO, CODIGO, ANDAR, ALA, TIPO, STATUS, ATIVO)
VALUES (SEQ_LEITOS.NEXTVAL, 'APT-202', '2', 'ALA B', 'APARTAMENTO', 'DISPONIVEL', 'S');

INSERT INTO LEITOS (ID_LEITO, CODIGO, ANDAR, ALA, TIPO, STATUS, ATIVO)
VALUES (SEQ_LEITOS.NEXTVAL, 'ISO-001', '3', 'ISOLAMENTO', 'ISOLAMENTO', 'DISPONIVEL', 'S');

COMMIT;
